config_version = 13

[bar]
order = [ "Eva" ]

    [bar.Eva]
    end = [ "media", "tray", "bluetooth", "volume", "clipboard", "notifications" ]
    font_family = "Adwaita Sans"
    margin_edge = 5
    margin_ends = 5
    padding = 11
    panel_overlap = 0
    position = "bottom"
    radius = 15
    start = [ "launcher", "workspaces" ]

        [bar.Eva.dead_zone.actions]
        middle = "exec noctalia msg panel-toggle noctalia/wallhaven:browser"

[control_center]
sidebar = "none"
sidebar_section = "none"
width = 820

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "notification"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
pre_action_fade_seconds = 0

[location]
auto_locate = true

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
offset_x = 10
offset_y = 10
position = "bottom_right"
show_actions = false

[osd]
offset_x = 10
offset_y = 10
position = "bottom_center"
position_vertical = "bottom_center"

[plugins]
enabled = [ "noctalia/wallhaven" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    enabled = false
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
clipboard_confirm_clear_history = false
clipboard_history_max_entries = 10
font_family = "Adwaita Sans"
password_style = "random"
polkit_agent = true

    [shell.launcher]
    categories = false
    show_app_origin_indicator = false
    show_icons = false
    sort_by_usage = false

    [shell.screenshot]
    directory = "/home/intimki/Картинки"
    save_to_file = false

    [shell.session]
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "5"
        variant = "destructive"

    [shell.shadow]
    alpha = 0.4999999888241291
    direction = "center"

[system.monitor]
enabled = false

[theme]
community_palette = "Mizuki-Akiyama"
source = "community"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "kitty", "qt" ]
    enable_community_templates = false

[wallpaper]
directory = "/home/intimki/Картинки"
directory_dark = "/home/intimki/Картинки"
directory_light = "/home/intimki/Картинки"

    [wallpaper.default]
    path = "/home/intimki/Картинки/wallhaven-3lw5g9.jpg"

    [wallpaper.last]
    path = "/home/intimki/Картинки/wallhaven-3lw5g9.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/intimki/Картинки/wallhaven-3lw5g9.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/intimki/Картинки/wallhaven-3lw5g9.jpg"

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.clock]
format = "%a. %-e, %H:%M"

[widget.launcher]
glyph = "terminal"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.notifications]
hide_when_no_unread = true

[widget.tray]
drawer = true